sensors:
  - name: cos
    file: /path/to/cos_acc.csv
    columns: 
      - time
      - timestamp
      - acc_x
      - acc_y
      - acc_z
    model_name: LocalOutlierFactor
    parameters:
      n_neighbors: 55
      contamination: 0.005
    window_size: 150
  - name: cor
    file: /path/to/cos_acc.csv
    columns: 
      - time
      - timestamp
      - accX
      - accY
      - accZ
    model_name: LocalOutlierFactor
    parameters:
      n_neighbors: 45
      contamination: 0.004
    window_size: 150
  - name: mat
    file: /path/to/mat.csv
    columns: 
      - time
      - timestamp
      - device1_value4
      - device1_value5
      - device1_value9
    model_name: LocalOutlierFactor
    parameters:
      n_neighbors: 35
      contamination: 0.02
    window_size: 150
  # - name: viva_acc
  #   file: /path/to/viva_hr.csv
  #   columns: 
  #     - time
  #     - timestamp
  #     - x
  #     - y
  #     - z
  #   model_name: LocalOutlierFactor
  #   parameters:
  #     n_neighbors: 35
  #     contamination: 0.01
  #   window_size: 100
plotting: true
